### ISSUE TITLE
error with Cloudflare R2

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#1104]
# Environment

0.7.0

Python

**Environment**:
Cloudflare R2

***
# Bug
trying to write a delta table into Cloudflare R2

```
import streamlit as st
import duckdb
con=duckdb.connect()
df=con.execute('''select * from 'C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/Parquet/0.1/lineitem.parquet' ''').arrow()
storage_options = {
"Region": "us-east-1",   
"AWS_ACCESS_KEY_ID":  st.secrets["aws_access_key_id_secret"],
"AWS_SECRET_ACCESS_KEY": st.secrets["aws_secret_access_key_secret"]   ,   
"AWS_ENDPOINT_URL" : st.secrets["endpoint_url_secret"] ,
}
from deltalake.writer import write_deltalake
write_deltalake("s3://delta/lineitem", df,mode="append",storage_options=storage_options)
```
I am getting this error

```
Traceback (most recent call last):
  File "c:\Users\mimoune.djouallah\Desktop\R2\S3DELTA__run.py", line 12, in <module>
    write_deltalake("s3://delta/lineitem", df,mode="append",storage_options=storage_options)
  File "C:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\deltalake\writer.py", line 255, in write_deltalake
    ds.write_dataset(
  File "C:\Users\mimoune.djouallah\AppData\Local\Programs\Python\Python310\lib\site-packages\pyarrow\dataset.py", line 988, in write_dataset
    _filesystemdataset_write(
  File "pyarrow\_dataset.pyx", line 2859, in pyarrow._dataset._filesystemdataset_write
deltalake.PyDeltaTableError: Generic S3 error: Error performing complete multipart request: response error "<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidPart</Code><Message>There was a problem with the 
multipart upload.</Message></Error>", after 0 retries: HTTP status client error (400 Bad Request) for url (https://c261c23c6a526f1de4652183768d7019.r2.cloudflarestorage.com/delta/lineitem/0-0454c103-9e7f-4181-b0a1-db8d5fc9d23f-0.parquet?uploadId=AM85x2Dc8wcGfU6ewzjf8WCr8QMkNcLe0Pda%2BAI0uE7VzaZUL2bnHqxynQBK%2FqhnXQ%2BeXa1TDjhozL82PxnpWm875J6o6MgkiCDco2%2BY7P1UIuQFOzFiyNgiDcGlYhBsUMZ4sqJiMaH5mP7p%2FN%2BF6H15mXDwcgkfJ%2BYmLwh4QQt7QmlKp%2Baz3NxQ%2BdDjbt5vTnMiTFjqMekwTPn41Ka4MfrRM95A21a4NVzSHud6CRMgaCXVfbEQT9H9QElbb7PUjo57s4MIoX3eP4U27%2BbcN5nlyiUuZdX6U%2F1N%2FjTw1JJDEEfkTaCA6pbzNM8HLVJHUVVSDFoSLpRXemZTpduknNU%3D)
PS C:\Users\mimoune.djouallah\Desktop\R2> 

```

**Comment by houqp** [comment]
probably a bug in the upstream object_store crate?

**Comment by Vad1mo** [comment]
Probably related issue in R2 https://community.cloudflare.com/t/cannot-upload-to-r2-from-pyarrow/426996/4

**Comment by wjones127** [comment]
I suspect this is the same root cause as in https://github.com/apache/arrow/issues/34363, since I based the object store implementation on that.

**Comment by rtyler** [comment]
@djouallah would you be able to validate that this is properly addressed in recent versions of the Python package? I believe we've incorporated the upstream fixes already

**Comment by djouallah** [comment]
yep !!! perfect, it works, thank you
![image](https://github.com/delta-io/delta-rs/assets/12554469/7448e417-f3d3-44b9-8f8b-ce9ab577565d)
