### ISSUE TITLE
Panic when deleting with predicate conflicts

### ISSUE THREAD

**Issue by alexwilcoxson-rel** [delta-io/delta-rs#1625]
# Environment

**Delta-rs version**: 0.14

**Binding**: Rust

**Environment**:
- **Cloud provider**: local test
- **OS**: macOS
- **Other**:

***
# Bug

**What happened**:
We have a concurrency test with deletes by a predicate using DeltaOps delete. When deltalake is attempting to check for conflicts there is a panic.

**What you expected to happen**:
Conflict error to be surfaced to our tests/application.

**How to reproduce it**:
I isolated it to this example test in [rust/src/operations/transaction/conflict_checker.rs](https://github.com/delta-io/delta-rs/blob/main/rust/src/operations/transaction/conflict_checker.rs).

```rust
    #[cfg(feature = "datafusion")]
    #[test]
    fn test_transaction_info_try_new() {
        let expr = col("foo").eq(lit("bar"));

        let state = DeltaTableState::from_actions(init_table_actions(), 0).unwrap();
        TransactionInfo::try_new(&state, Some(expr.canonical_name()), &vec![], false).unwrap();
    }
```

**More details**:
There seem to be two issues
* TransactionInfo::try_new accepts String predicate. [Delete provides this via canonical_name](https://github.com/delta-io/delta-rs/blob/main/rust/src/operations/delete.rs#L265). This panics because the underlying [parse code](https://github.com/delta-io/delta-rs/blob/main/rust/src/operations/transaction/state.rs#L107-L128) that uses a [DummyContextProvider for datafusion has unimplemented!()](https://github.com/delta-io/delta-rs/blob/main/rust/src/operations/transaction/state.rs#L345-L374).

```
running 4 tests
test operations::transaction::conflict_checker::tests::test_can_downgrade_to_snapshot_isolation ... ok
thread 'operations::transaction::conflict_checker::tests::test_transaction_info_try_new' panicked at 'not implemented', rust/src/operations/transaction/state.rs:356:9
stack backtrace:
test operations::transaction::conflict_checker::tests::test_allowed_concurrent_actions ... ok
test operations::transaction::conflict_checker::tests::test_disallowed_concurrent_actions ... ok
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:117:5
   3: get_function_meta
             at ./src/operations/transaction/state.rs:356:9
   4: sql_function_to_expr<deltalake::operations::transaction::state::DummyContextProvider>
             at /Users/alex.wilcoxson/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datafusion-sql-30.0.0/src/expr/function.rs:50:27
   5: sql_expr_to_logical_expr_internal<deltalake::operations::transaction::state::DummyContextProvider>
             at /Users/alex.wilcoxson/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datafusion-sql-30.0.0/src/expr/mod.rs:428:17
   6: sql_expr_to_logical_expr<deltalake::operations::transaction::state::DummyContextProvider>
             at /Users/alex.wilcoxson/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datafusion-sql-30.0.0/src/expr/mod.rs:88:40
   7: sql_to_expr<deltalake::operations::transaction::state::DummyContextProvider>
             at /Users/alex.wilcoxson/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datafusion-sql-30.0.0/src/expr/mod.rs:122:24
   8: parse_predicate_expression<alloc::string::String>
             at ./src/operations/transaction/state.rs:127:12
   9: {closure#0}
             at ./src/operations/transaction/conflict_checker.rs:118:25
  10: map<alloc::string::String, core::result::Result<datafusion_expr::expr::Expr, deltalake::errors::DeltaTableError>, deltalake::operations::transaction::conflict_checker::{impl#0}::try_new::{closure_env#0}>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:1075:29
  11: try_new
             at ./src/operations/transaction/conflict_checker.rs:117:31
  12: test_transaction_info_try_new
             at ./src/operations/transaction/conflict_checker.rs:673:18
  13: {closure#0}
             at ./src/operations/transaction/conflict_checker.rs:669:40
  14: call_once<deltalake::operations::transaction::conflict_checker::tests::test_transaction_info_try_new::{closure_env#0}, ()>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test operations::transaction::conflict_checker::tests::test_transaction_info_try_new ... FAILED
```

* Locally with the above test and returning `None` instead of `unimplemented!()` it still fails because `canonical_name()` would return `foo = Utf8("bar")` which is not valid datafusion SQL.

```thread 'operations::transaction::conflict_checker::tests::test_transaction_info_try_new' panicked at 'called Result::unwrap() on an Err value: Generic("Error during planning: Invalid function 'utf8'.\nDid you mean 'atan'?")', rust/src/operations/transaction/conflict_checker.rs:674:95```

**Comment by Blajda** [comment]
This is related to: https://github.com/apache/arrow-datafusion/issues/7165
Maybe for a quick fix we can copy the canonical func to delta and make the changes we need.
