### ISSUE TITLE
get_add_actions fails with deltalake 0.13

### ISSUE THREAD

**Issue by aersam** [delta-io/delta-rs#1835]
# Environment

**Delta-rs version**: 0.13.0

**Binding**: Python

**Environment**:
- **Cloud provider**:
- **OS**: Windows Server / Windows 10 (both tested)
- **Other**:

***
# Bug

**What happened**:

`get_add_actions` fails, with both flatten=True/False:

```python
from deltalake import DeltaTable
dt = DeltaTable("tbl")
dt.get_add_actions()
```

gives:

```
thread '<unnamed>' panicked at crates\deltalake-core\src\table\state_arrow.rs:175:53:
called Option::unwrap() on a None value
stack backtrace:
   0:     0x7ffc6523beca - BrotliDecoderVersion
   1:     0x7ffc65263dbb - BrotliDecoderVersion
   2:     0x7ffc65237231 - BrotliDecoderVersion
   3:     0x7ffc6523bc4a - BrotliDecoderVersion
   4:     0x7ffc6523e6ba - BrotliDecoderVersion
   5:     0x7ffc6523e328 - BrotliDecoderVersion
   6:     0x7ffc6523ed6e - BrotliDecoderVersion
   7:     0x7ffc6523ec1a - BrotliDecoderVersion
   8:     0x7ffc6523cb89 - BrotliDecoderVersion
   9:     0x7ffc6523e960 - BrotliDecoderVersion
  10:     0x7ffc653a5365 - BrotliDecoderVersion
  11:     0x7ffc653a5412 - BrotliDecoderVersion
  12:     0x7ffc62951a14 - PyInit__internal
  13:     0x7ffc62746857 - BrotliDecoderSetParameter
  14:     0x7ffc6271b8ce - BrotliDecoderSetParameter
  15:     0x7ffc627377c1 - BrotliDecoderSetParameter
  16:     0x7ffca3f8961e - PyUnicode_ToDecimalDigit
  17:     0x7ffca3ed494b - PyObject_Vectorcall
  18:     0x7ffca3ed5da4 - PyEval_EvalFrameDefault
  19:     0x7ffca3ef2f73 - PyMapping_Check
  20:     0x7ffca3ef27db - PyEval_EvalCode
  21:     0x7ffca3f62582 - Py_SourceAsString
  22:     0x7ffca3f624fe - Py_SourceAsString
  23:     0x7ffca40a3df4 - PyThread_tss_is_created
  24:     0x7ffca4006b99 - PyRun_SimpleFileObject
  25:     0x7ffca40078e0 - PyRun_AnyFileObject
  26:     0x7ffca4007387 - PyDict_DelItemString
  27:     0x7ffca4007243 - PyDict_DelItemString
  28:     0x7ffca3fc0d80 - Py_RunMain
  29:     0x7ffca3fc0a2d - Py_RunMain
  30:     0x7ffca3ec81b5 - Py_Main
  31:     0x7ff62cf51230 - <unknown>
  32:     0x7ffcca5684d4 - BaseThreadInitThunk
  33:     0x7ffccbf61791 - RtlUserThreadStart
Traceback (most recent call last):
  File "k:\Software\AZCopy\CSVGetter\test_ds.py", line 5, in <module>
    dt.get_add_actions()
  File "K:\Software\AZCopy\CSVGetter\.venv\Lib\site-packages\deltalake\table.py", line 859, in get_add_actions
    return self._table.get_add_actions(flatten)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called Option::unwrap() on a None value
```

**What you expected to happen**:
Well, it should not panic

**How to reproduce it**:

Repo is here: [tester.zip](https://github.com/delta-io/delta-rs/files/13317653/tester.zip) 

**More details**:

**Comment by aersam** [comment]
Probably a duplicate of https://github.com/delta-io/delta-rs/issues/1579
However it's worse now since setting flatten=True does not help anymore
