### ISSUE TITLE
Cannot convert data-reader-map golden table to pyarrow

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#217]
# Environment

**Delta-rs version**: bd5f431f5a000ccd3d09b4b981fb0c802536403e

**Environment**:
- **Cloud provider**:
- **OS**: Linux/amd64
- **Other**:

***
# Bug

When running the following simple code against the golden data set:'s [data-readers-map](https://github.com/delta-io/connectors/tree/master/golden-tables/src/test/resources/golden/data-reader-map) table

```python
from deltalake import DeltaTable
from pprint import pprint

if __name__ == '__main__':
    dt = DeltaTable('s3://delta/golden/data-reader-map')
    print(f'Table version: {dt.version()}')
    for f in dt.files():
        print(f' - {f}')

    df = dt.to_pyarrow_table().to_pandas()
    pprint(df)
```

**What happened**:

```
% python query-demo.py
Table version: 0
 - part-00000-d9004e55-077b-4728-9ee6-b3401faa46ba-c000.snappy.parquet
 - part-00001-3d30d085-4cde-471e-a396-12af34a70812-c000.snappy.parquet
Traceback (most recent call last):
  File "query-demo.py", line 10, in <module>
    df = dt.to_pyarrow_table().to_pandas()
  File "/home/tyler/source/github/delta-io/delta-rs/python/deltalake/table.py", line 225, in to_pyarrow_table
    return self.to_pyarrow_dataset().to_table()
  File "/home/tyler/source/github/delta-io/delta-rs/python/deltalake/table.py", line 213, in to_pyarrow_dataset
    schema=self.pyarrow_schema(),
  File "/home/tyler/source/github/delta-io/delta-rs/python/deltalake/table.py", line 184, in pyarrow_schema
    return pyarrow_schema_from_json(self._table.arrow_schema_json())
  File "/home/tyler/source/github/delta-io/delta-rs/python/deltalake/schema.py", line 289, in pyarrow_schema_from_json
    arrow_fields = [pyarrow_field_from_dict(field) for field in schema_json["fields"]]
  File "/home/tyler/source/github/delta-io/delta-rs/python/deltalake/schema.py", line 289, in <listcomp>
    arrow_fields = [pyarrow_field_from_dict(field) for field in schema_json["fields"]]
  File "/home/tyler/source/github/delta-io/delta-rs/python/deltalake/schema.py", line 275, in pyarrow_field_from_dict
    pyarrow_datatype_from_dict(field),
  File "/home/tyler/source/github/delta-io/delta-rs/python/deltalake/schema.py", line 217, in pyarrow_datatype_from_dict
    field = json_dict["children"][0]
IndexError: list index out of range
```

**What you expected to happen**:

I'm not sure if this data set is corrupted to begin with, but I have a feeling that marshalling maps out of Rust into Python is not working somehow. Just a guess.

**How to reproduce it**:

**More details**:

**Comment by houqp** [comment]
Most likely an edge case that was not handled during the json deserialization. I think this kind of errors could be prevented at build time with https://github.com/delta-io/delta-rs/issues/95.

**Comment by fvaleye** [comment]
The error is a bit strange for me: 
https://github.com/apache/arrow/blob/master/rust/arrow/src/datatypes/field.rs#L226

Looking at the code, a pyarrow list must have children...
