### ISSUE TITLE
`to_pyarrow_table()` on a table in S3 kept getting "Generic S3 error: error decoding response body"

### ISSUE THREAD

**Issue by k-ye** [delta-io/delta-rs#2595]
# Environment

**Delta-rs version**: `deltalake==0.18.1`

**Binding**:  Python

**Environment**: 
- **Cloud provider**: AWS S3
- **OS**: Linux
- **Other**:
  - Python 3.10.4
  - `pyarrow==16.1.0`
  - `pyarrow-hotfix==0.6`

***
# Bug

**What happened**:

Trying to do a simple table loading from S3, but kept getting this `OSError: Generic S3 error: error decoding response body`

```py
table = DeltaTable(table_uri, storage_options=storage_options)
print(f"version: {table.version()}")
print(f"schema: {table.schema()}")
print(table.files())

ts = time.time()
df = table.to_pyarrow_table()
```

```
version: 0
schema: Schema([Field(id, PrimitiveType("string"), nullable=True), Field(path, PrimitiveType("string"), nullable=True)])
['0-e03dac34-16a0-4b6e-82c8-fd1098d1bf45-0.parquet']
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    df = table.to_pyarrow_table()
  File "***/lib/python3.10/site-packages/deltalake/table.py", line 1161, in to_pyarrow_table
    return self.to_pyarrow_dataset(
  File "pyarrow/_dataset.pyx", line 562, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 3804, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 88, in pyarrow.lib.check_status
OSError: Generic S3 error: error decoding response body
```

Stack shows that this is actually in `pyarrow`. Not sure if it possible to tweak `pyarrow`'s behavior with S3 from `deltalake`.

**What you expected to happen**:

I can get the pyarrow table.

**How to reproduce it**:

**More details**:

I have verified the integrity of this table with these methods:

1. Cloning the table locally, then load from there. `to_pyarrow_table()` runs fine.
2. Reading the S3 table with `duckdb` (and its `delta` extension). Worked fine, too.

**Comment by k-ye** [comment]
Seems related to https://github.com/delta-io/delta-rs/issues/2301 and https://github.com/delta-io/delta-rs/issues/2592

**Comment by ion-elgreco** [comment]
@k-ye can you try deltalake 0.19.1 please and report back if you see improvements

**Comment by k-ye** [comment]
> @k-ye can you try deltalake 0.19.1 please and report back if you see improvements

I've done a few tests:

- On a U.S. machine (but not on AWS), this generally works now. Occasionally it was able to finish the script execution, but the process ended with

```
terminate called without an active exception
Aborted
```

- On a CN machine behind a VPN, I could still bump into this error, though.

**Comment by ion-elgreco** [comment]
> > @k-ye can you try deltalake 0.19.1 please and report back if you see improvements
> 
> I've done a few tests:
> 
> * On a U.S. machine (but not on AWS), this generally works now. Occasionally it was able to finish the script execution, but the process ended with
> 
> ```
> terminate called without an active exception
> Aborted
> ```
> 
> * On a CN machine behind a VPN, I could still bump into this error, though.

Hmm that's a C++ error

Regarding VPN's, I would defer to what Tustvold said: https://github.com/apache/arrow-rs/issues/5882#issuecomment-2288593022

**Comment by k-ye** [comment]
> I have the same issue, @k-ye were you able to solve this?

Hi @shriram-louisa ,

Sorry I didn't follow up on this. We were just testing the water when I filed this issue, and have sinced moved on to other solutions...

**Comment by ion-elgreco** [comment]
> Thank you for the response 🙌 @k-ye 

What delta-rs version are you using?

**Comment by sim-san** [comment]
I am getting the same error. Do know what causes the error?

delta-rs 0.19.1

**Comment by ion-elgreco** [comment]
@shriram-louisa @sim-san  how stable is your connection, are you running this behind a VPN, what's the throughput, how big is your table?

**Comment by ion-elgreco** [comment]
Have any of you tired increasing the timeout to 60s or 120s? `storage_options = {"timeout":"120s"}`

**Comment by ion-elgreco** [comment]
> > Have any of you tired increasing the timeout to 60s or 120s? `storage_options = {"timeout":"120s"}`
> 
> The delta table has a file size of around 700MB. The increase of the timeout solved the problem.
> But where can I find further documentation about the possible storage_options ?

You will have to check the object_store crate documentation, and then choose your storage aws S3, it shows the config keys

**Comment by junhl** [comment]
This seems to also happen when querying a longer data column.

```
table = DeltaTable("...") # WITHOUT timeout addition
df = table.to_pandas(column=["some_id"], filters=[("some_id", "in", ["id1", "id2"])]) # works fine in 2 seconds
df = table.to_pandas(column=["some_id", "raw_data"], filters=[("some_id", "in", ["id1", "id2"])]) # gives decoding error after few mins - raw_data is JSON string about few kb per row.

table = DeltaTable("...", storage_options = {"timeout":"120s"}) # WITH timeout addition
df = table.to_pandas(column=["some_id"], filters=[("some_id", "in", ["id1", "id2"])]) # works fine in 2 seconds
df = table.to_pandas(column=["some_id", "raw_data"], filters=[("some_id", "in", ["id1", "id2"])]) # works, but took a few mins
```

**Comment by Tom-Newton** [comment]
I tried the latest version of delta-rs (`python-v0.22.0`) and I even tried modifying it to make use of https://github.com/apache/arrow-rs/pull/6612, but I can still reproduce the problem. I'll try to investigate further.

**Comment by ion-elgreco** [comment]
> I tried the latest version of delta-rs (`python-v0.22.0`) and I even tried modifying it to make use of https://github.com/apache/arrow-rs/pull/6612, but I can still reproduce the problem. I'll try to investigate further. 

It already uses a separate runtime so probably that didn't have much effect

**Comment by ryzhyk** [comment]
I am also getting this error. It seems to be triggered by larger Parquet files (I started seeing it after running `OPTIMIZE` on a table with 3M records, which consolidated many smaller files into a single 180MB Parquet file). Setting `"timeout":"120s"` seems to have helped.

**Comment by ryzhyk** [comment]
I am still seeing a similar issue even with `"timeout": "120s"`. Before setting the timeout, I was seeing instances of `DataFusionError::ArrowError(ArrowError::ExternalError(error), _)`, where the inner error was an S3 timeout. After setting `"timeout": "120s"`, I am now getting `DataFusionError::ParquetError(ParquetError::External(error))`, where the inner error is one of "Generic S3 error: error decoding response body" or "Error after 2 retries in 250.911442071s, max_retries:10, retry_timeout:180s, source:error sending request for url REDACTED", both of which indicate timeouts I think. This seems much more likely to happen when the program is doing a lot of CPU and IO-intensive work.

I'd appreciate any hints on what could be causing these errors.

**Comment by ion-elgreco** [comment]
@ryzhyk you can read through all these:

 https://github.com/apache/arrow-rs/issues/7242
https://github.com/apache/datafusion/pull/14286#issuecomment-2626852759
https://github.com/delta-io/delta-rs/pull/3162

**Comment by ryzhyk** [comment]
Thanks, @ion-elgreco , these are very helpful resources.

**Comment by alamb** [comment]
I spent some time today tracking down a similar issue in DataFusion that I think is likely the same underlying cause as many of the symptoms reported on this issue
- https://github.com/apache/datafusion/issues/15067

**Comment by alamb** [comment]
I think this is the solution to these errors (automatically retry on error)
- https://github.com/delta-io/delta-rs/issues/2595

**Comment by ryzhyk** [comment]
@alamb , did you mean to reference https://github.com/apache/arrow-rs/issues/7242?

**Comment by alamb** [comment]
> [@alamb](https://github.com/alamb) , did you mean to reference [apache/arrow-rs#7242](https://github.com/apache/arrow-rs/issues/7242)?

Yes, thank you @ryzhyk  -- updated 🤦

**Comment by ryzhyk** [comment]
I think that chunked requests described here are also essential in some cases (slow or overloaded connection, and large row groups): https://github.com/apache/arrow-rs/issues/7251

**Comment by alamb** [comment]
> I think that chunked requests described here are also essential in some cases (slow or overloaded connection, and large row groups): [apache/arrow-rs#7251](https://github.com/apache/arrow-rs/issues/7251)

I thought so too @ryzhyk  but today I was convinced otherwise (see https://github.com/apache/arrow-rs/issues/7251#issuecomment-2733957472 for details)

> @crepererum rightly pointed out that implementing retries (aka https://github.com/apache/arrow-rs/issues/7242) would be better than splitting into smaller requests to make a timeout as the retry mechanism automatically adjusts to current network conditions

**Comment by ion-elgreco** [comment]
@alamb that's great! :)

**Comment by ion-elgreco** [comment]
Resolved upstream and this is available in object_store 0.12.2 which is used in python deltalake 1.1+

**Comment by alamb** [comment]
🎉
