### ISSUE TITLE
Python DeltaTable does not support writes in multiple threads

### ISSUE THREAD

**Issue by PeterKeDer** [delta-io/delta-rs#2958]
# Environment

**Delta-rs version**: 0.20.1

**Binding**: python

**Environment**:
- **Cloud provider**:
- **OS**: macOS
- **Other**:

***
# Bug

**What happened**:

Using the same `DeltaTable` across multiple threads in `write_deltalake` causes the error
```
RuntimeError: Already borrowed
```

This is not an issue if we use the table URI directly.

**What you expected to happen**:

Writes should work in a multithreaded environment.

**How to reproduce it**:

```python
from concurrent.futures import ThreadPoolExecutor
from deltalake import DeltaTable, write_deltalake
import polars as pl

path = 'some local path'
table = pl.DataFrame({'a': [1,2,3]}).to_arrow()
write_deltalake(path, table)

dt = DeltaTable(path)

with ThreadPoolExecutor() as exe:
    list(exe.map(lambda _: write_deltalake(dt, table, mode='append'), range(2)))
```
produces
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/peter.ke/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/Users/peter.ke/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/Users/peter.ke/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/peter.ke/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/peter.ke/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<stdin>", line 2, in <lambda>
  File "/Users/peter.ke/.pyenv/versions/3.10.13/lib/python3.10/site-packages/deltalake/writer.py", line 302, in write_deltalake
    table.update_incremental()
  File "/Users/peter.ke/.pyenv/versions/3.10.13/lib/python3.10/site-packages/deltalake/table.py", line 1258, in update_incremental
    self._table.update_incremental()
RuntimeError: Already borrowed
```

**More details**:

Cause of error:
- `write_deltalake` calls `write_to_deltalake` from rust to write, which borrows the `RawDeltaTable` immutably while releasing the GIL. The immutable borrow means theoretically writes in multiple threads should be fine
- However, `write_deltalake` also calls `table.update_incremental()`, which borrows the `RawDeltaTable` mutably
- Since GIL was released in `write_to_deltalake`, another thread running `write_deltalake` will try to mutably borrow the previously immutably borrowed `RawDeltaTable` and fails

From my brief investigation, I see two potential solutions:
- The Rust API exposed to python could benefit from being refactored to be more immutable so it fits better in a multi-threaded environment. e.g. on the rust side, `update_incremental` can return a new `DeltaTable` rather than mutating the existing one- similarly for other internals like `DeltaTableState` or `Snapshot`.
 
  This should be similar performance/memory wise, since cloning a `Snapshot` seems relatively cheap given that the bulk `files` uses arrow. However, this looks like a large-ish refactor because a lot of the internals expose mutable APIs.

- Remove `update_incremental` from `write_deltalake` (or add a flag to disable it). We'd just need to ensure `write_to_deltalake` returns an updated `RawDeltaTable` so `table._table` can kept updated.

**Comment by PeterKeDer** [comment]
Actually the easiest solution might be to just clone the `RawDeltaTable` before we pass it into `write_to_deltalake` so it is not borrowed.

**Comment by brurucy** [comment]
I believe you could get around it with multiprocessing (using `spawn`).

**Comment by PeterKeDer** [comment]
> I believe you could get around it with multiprocessing (using `spawn`).

True, that does work. `DeltaTable` is not picklable though so it's a bit annoying. Since `write_deltalake` releases the GIL, I believe like the intention is to support multithreaded writes.

**Comment by houqp** [comment]
I think it's best to make the `update_incremental` call optional, seems unnecessary to always incur this overhead in the circumstances when the caller already know it has an up-to-date table instance.

**Comment by nicolo-barboni** [comment]
I am facing this issue with the latest release (1.0.2) but not with the 0.25 version. I used the same code snippet to reproduce the error posted by @PeterKeDer.
 ```
nicolo@NICOLO-VERSIRO delta_lake_function_test % uv run --no-project --with polars --with deltalake==0.25 --with pyarrow test.py
[2025-07-10T09:13:47Z ERROR deltalake_core::operations::transaction] The transaction 10 already exists, will retry!
[2025-07-10T09:13:47Z WARN  deltalake_core::operations::transaction] Attempting to write a transaction 10 but the underlying table has been updated to 10
    DefaultLogStore(/Users/nicolo/Documents/optibid/backend/apps/delta_lake_function_test/some%20local%20path/)
nicolo@NICOLO-VERSIRO delta_lake_function_test % uv run --no-project --with polars --with deltalake==1.0.2 --with pyarrow test.py
Traceback (most recent call last):
  File "/Users/nicolo/Documents/optibid/backend/apps/delta_lake_function_test/test.py", line 12, in <module>
    list(exe.map(lambda _: write_deltalake(dt, table, mode='append'), range(2)))
  File "/Users/nicolo/.local/share/uv/python/cpython-3.9.19-macos-aarch64-none/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/Users/nicolo/.local/share/uv/python/cpython-3.9.19-macos-aarch64-none/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Users/nicolo/.local/share/uv/python/cpython-3.9.19-macos-aarch64-none/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/nicolo/.local/share/uv/python/cpython-3.9.19-macos-aarch64-none/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/nicolo/Documents/optibid/backend/apps/delta_lake_function_test/test.py", line 12, in <lambda>
    list(exe.map(lambda _: write_deltalake(dt, table, mode='append'), range(2)))
  File "/Users/nicolo/.cache/uv/archive-v0/208dKU2A5MYfnmcp4GhIq/lib/python3.9/site-packages/deltalake/writer/writer.py", line 126, in write_deltalake
    table._table.write(
RuntimeError: Already borrowed
 ```

**Comment by nicolo-barboni** [comment]
I investigated a bit more and it seems like the change was introduced in version 0.25.2.
 ```
nicolo@NICOLO-VERSIRO data_processing_v2 % uv run --no-project --with deltalake==0.25.1 --with pandas test.py
[2025-07-11T08:13:17Z ERROR deltalake_core::operations::transaction] The transaction 10 already exists, will retry!
[2025-07-11T08:13:17Z WARN  deltalake_core::operations::transaction] Attempting to write a transaction 10 but the underlying table has been updated to 10
    DefaultLogStore(/Users/nicolo/Documents/optibid/backend/apps/data_processing_v2/some%20local%20path/)
nicolo@NICOLO-VERSIRO data_processing_v2 % uv run --no-project --with deltalake==0.25.2 --with pandas test.py
Installed 8 packages in 74ms
Traceback (most recent call last):
  File "/Users/nicolo/Documents/optibid/backend/apps/data_processing_v2/test.py", line 12, in <module>
    list(exe.map(lambda _: write_deltalake(dt, table, mode='append'), range(2)))
  File "/opt/homebrew/Cellar/python@3.12/3.12.10_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.10_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.10_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.10_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.12/3.12.10_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolo/Documents/optibid/backend/apps/data_processing_v2/test.py", line 12, in <lambda>
    list(exe.map(lambda _: write_deltalake(dt, table, mode='append'), range(2)))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolo/.cache/uv/archive-v0/EFibTYRTkVpbUstltiMW-/lib/python3.12/site-packages/deltalake/writer.py", line 324, in write_deltalake
    table._table.write(
RuntimeError: Already borrowed
 ```
