### ISSUE TITLE
write_delta failed pyarrow.lib.ArrowInvalid: Integer value 133 not in range: 0 to 127

### ISSUE THREAD

**Issue by MDGSF** [delta-io/delta-rs#3086]
# Environment

**Delta-rs version**:
deltalake            0.22.3

**Binding**: 

**Environment**: python 3.12
- **Cloud provider**:
- **OS**: wsl ubuntu20.04
- **Other**:

***
# Bug

**What happened**:

```
import rerun as rr
from deltalake import write_deltalake

recording = rr.dataframe.load_recording("test.rrd")
view = recording.view(index="log_time", contents="/**")
df = view.select().read_pandas()

for col in df.select_dtypes(include=["datetime64[ns]"]).columns:
    df[col] = df[col].astype("datetime64[us]")

write_deltalake("tmp/demo", df)
```

error log:

```
Traceback (most recent call last):
  File "/home/dev/git/dev/bicv/rerun/demos/demo03_rrd_to_deltalake_pandas/demo03.py", line 11, in <module>
    write_deltalake("tmp/demo", df)
  File "/home/dev/anaconda3/envs/rerun/lib/python3.12/site-packages/deltalake/writer.py", line 317, in write_deltalake
    data, schema = _convert_data_and_schema(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/anaconda3/envs/rerun/lib/python3.12/site-packages/deltalake/writer.py", line 679, in _convert_data_and_schema
    data = convert_pyarrow_table(pa.Table.from_pandas(data), conversion_mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/anaconda3/envs/rerun/lib/python3.12/site-packages/deltalake/schema.py", line 187, in convert_pyarrow_table
    data = data.cast(schema).to_reader()
           ^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 4683, in pyarrow.lib.Table.cast
  File "pyarrow/table.pxi", line 593, in pyarrow.lib.ChunkedArray.cast
  File "/home/dev/anaconda3/envs/rerun/lib/python3.12/site-packages/pyarrow/compute.py", line 405, in cast
    return call_function("cast", [arr], options, memory_pool)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_compute.pyx", line 598, in pyarrow._compute.call_function
  File "pyarrow/_compute.pyx", line 393, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Integer value 133 not in range: 0 to 127
```

**What you expected to happen**:

I hope it can write delta success

**How to reproduce it**:

**More details**:

**Comment by ion-elgreco** [comment]
Please share an MRE that can be executed on its own instead of uploading a zip file.

**Comment by MDGSF** [comment]
I think I know why, because Delta Lake does not support unsigned integers. Thanks so much.

**Comment by MDGSF** [comment]
I think I know why, because Delta Lake does not support unsigned integers. Thanks so much.
