### ISSUE TITLE
Schema type must be struct

### ISSUE THREAD

**Issue by blogle** [delta-io/delta-rs#409]
# Environment

**Delta-rs version**: master

**Binding**: native/rust

**Environment**: 
- **Cloud provider**: Google Cloud
- **OS**: GNU/Linux (NixOS 21.11.20210730.04c25b8 (Porcupine))
- **Other**: N/A

***
# Bug

**What happened**:
Following the test code as an example for how to create a new `DeltaTable` https://github.com/delta-io/delta-rs/blob/9196ff49bc147b36339b4901624229473092b024/rust/src/delta.rs#L1666, I was under the assumption the type name there could be arbitrary. However subsequently loading from spark results in the following error 
```
scala> val test = spark.read.format("delta").load("gs://delta-time/new_table")
java.lang.IllegalArgumentException: Failed to convert the JSON string '{"type":"test","fields":[{"name":"X","type":"integer","nullable":true,"metadata":{}},{"name":"Y","type"
:"integer","nullable":true,"metadata":{}}]}' to a data type.
  at org.apache.spark.sql.types.DataType$.parseDataType(DataType.scala:239)
  at org.apache.spark.sql.types.DataType$.fromJson(DataType.scala:169)
  at org.apache.spark.sql.delta.actions.Metadata.$anonfun$schema$1(actions.scala:336)
  at scala.Option.map(Option.scala:230)
  at org.apache.spark.sql.delta.actions.Metadata.schema$lzycompute(actions.scala:335)
  at org.apache.spark.sql.delta.actions.Metadata.schema(actions.scala:334)
  at org.apache.spark.sql.delta.DeltaLog$$anon$1.<init>(DeltaLog.scala:350)
  at org.apache.spark.sql.delta.DeltaLog.createRelation(DeltaLog.scala:347)
  at org.apache.spark.sql.delta.catalog.DeltaTableV2.toBaseRelation(DeltaTableV2.scala:143)
  at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:171)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:354)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:326)
  at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:306)
  at scala.Option.map(Option.scala:230)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:266)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:240)
  ... 47 elided
```

**What you expected to happen**:
Tables created from delta-rs should be readable by other implementations of delta lake, eg the canonical spark implementation.

**How to reproduce it**:
write a table with a schema where the type name is anything other than "struct". eg 
```
	let test_schema = Schema::new(
		"test".to_string(),
		vec![
			SchemaField::new(
				"x".to_string(),
				SchemaDataType::primitive("integer".to_string()),
				true,
				HashMap::new(),
			),
			SchemaField::new(
				"y".to_string(),
				SchemaDataType::primitive("integer".to_string()),
				true,
				HashMap::new(),
			),
		],
	);

```

**More details**:
in the canonical implementation of delta, tables are created by invoking `CreateTableStatement`
https://github.com/delta-io/delta/blob/4d405ff32fe7622add1c1f43abae850e065322ec/core/src/main/scala/io/delta/tables/DeltaTableBuilder.scala#L325
looking into the spark internals
https://jaceklaskowski.github.io/mastering-spark-sql-book/logical-operators/CreateTableStatement/
we see that the table schema must be of a struct type
https://jaceklaskowski.github.io/mastering-spark-sql-book/types/StructType/

At the minimum, the test code should be augmented to use `"struct"` as the schema type. A more pronounced change would be removing the type field from the struct entirely and always serializing the schema type as `"struct"` or removing it as an argument to the `Schema` constructor, and always instantiate the struct with the correct type.
`https://github.com/delta-io/delta-rs/blob/9196ff49bc147b36339b4901624229473092b024/rust/src/schema.rs#L167

**Comment by Smurphy000** [comment]
Ya, I guess this wasn't a problem prior to adding the `create` method for a `DeltaTable` . We could enforce the `"struct"` by checking the passed in metadata in  `create`  and raising an appropriate error if it isn't, thus making it on the caller to handle the schema creation (update the test to reflect this), or as you suggested, put it on the `Schema`.

**Comment by houqp** [comment]
On top of checking for the type string in create table call, we should also just remove the `type` argument in `Schema::new` method: https://github.com/delta-io/delta-rs/blob/9196ff49bc147b36339b4901624229473092b024/rust/src/schema.rs#L178. 

Within the new method implementation, we can always set type to the `struct` string.
