### ISSUE TITLE
Can't use corporate proxy configuration with S3

### ISSUE THREAD

**Issue by xfrancois** [delta-io/delta-rs#637]
I try to access delta lake files on S3 with the python API :

```python
table_path = f's3://path'
handler = DeltaStorageHandler(table_path)
```

It works well on local environment, but doesn't work on an environment with corporate proxy settings. I try to add HTTP_PROXY and HTTPS_PROXY but it doesn't seem to be taken into account.

```
Traceback (most recent call last):
  File "/usr/src/app/./main.py", line 59, in <module>
    main()
  File "/usr/src/app/./main.py", line 54, in main
    download_merged_cdr(business_unit, ingestion_date)
  File "/usr/src/app/./main.py", line 27, in download_merged_cdr
    dt = DeltaTable(table_path)
  File "/usr/local/lib/python3.9/site-packages/deltalake/table.py", line 85, in __init__
    self._table = RawDeltaTable(
deltalake.PyDeltaTableError: Failed to load checkpoint: Failed to read checkpoint content: Failed to read S3 object content: Error during dispatch: error trying to connect: tcp connect error: Connection timed out (os error 110)
```

Is it possible to set proxy settings and how ?

It may be possible to edit the `create_http_client` function in mod.rs https://github.com/delta-io/delta-rs/blob/a7510a74b553effc408d35b92ab8490a870b0c4b/rust/src/storage/s3/mod.rs#L419-L423 as done here : https://github.com/rusoto/rusoto/issues/1172#issuecomment-470175313 by injecting a ProxyConnector to S3Client.

```rust
  use hyper::client::HttpConnector;
  use hyper_proxy::{Proxy, ProxyConnector, Intercept};
  use rusoto_core::request::HttpClient;
  use rusoto_core::credential::ChainProvider;

  let client = match env::var("HTTPS_PROXY") {
      Ok(proxy_uri) => {
          let proxy = Proxy::new(Intercept::All, proxy_uri.parse()?);
          let proxy_connector = ProxyConnector::from_proxy(
              HttpConnector::new(4), proxy
          )?;

          let http = HttpClient::from_connector(proxy_connector);
          S3Client::new_with(http, ChainProvider::new(), region)
      },
      Err(_) => S3Client::new(region)
  };
```

**Comment by xfrancois** [comment]
I did try my best, but please review carefully because it was my first time dealing with Rust. The code in the PR has been tested on the corporate proxy environment and it seems to work.
