### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by vsytchenko-exos** [delta-io/delta-rs#776]
# Environment
Python : 3.9.13
**Delta-rs version**: 0.5.8
***
# Bug
Istall the lib ` pip install deltalake`
try to import DeltaTable
`from deltalake import DeltaTable`

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/...venv/lib/python3.9/site-packages/deltalake/__init__.py", line 5, in <module>
    from .writer import write_deltalake
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/...venv/lib/python3.9/site-packages/deltalake/writer.py", line 29, in <module>
    from typing_extensions import Literal
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'typing_extensions'
```
if I then install typing_extensions manually, it works.

**Comment by roeap** [comment]
This should be addressed in the next release #762.

**Comment by roeap** [comment]
@vsytchenko-exos - can you validate if this works now using 0.6?

**Comment by vsytchenko-exos** [comment]
@roeap it works. Thank you

**Comment by roeap** [comment]
Great, closing this then :)
