### ISSUE TITLE
Azure read with inline credentials broken in 0.6.2

### ISSUE THREAD

**Issue by george-zubrienko** [delta-io/delta-rs#881]
# Environment WSL2 (Ubuntu 20.04)

**Delta-rs version**: 0.6.2

**Binding**: Python (3.9)

**Environment**:
- **Cloud provider**: Azure
- **OS**: Ubuntu 20.04
- **Other**: -

***
# Bug

**What happened**:

Running this code against ADLS2 table throws in 0.6.2:

```
pyarrow_ds = DeltaTable('az://tmp/dev_george_t/some_data', version=version,
                            storage_options={
  'AZURE_STORAGE_ACCOUNT_NAME': '...',
  'AZURE_STORAGE_ACCOUNT_KEY': '...'
}).to_pyarrow_dataset(parquet_read_options=ParquetReadOptions(coerce_int96_timestamp_unit="ms"))

pyarrow_table: Table = pyarrow_ds.to_table(filter=row_filter, columns=columns)
```

Stack:

```
thread '<unnamed>' panicked at 'dispatch dropped without returning error', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/client/conn.rs:329:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'dispatch dropped without returning error', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/client/conn.rs:329:35
thread '<unnamed>' panicked at 'dispatch dropped without returning error', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/client/conn.rs:329:35
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/users/gzu/source/repos/github/proteus/proteus/storage/delta_lake/_functions.py", line 49, in load
    pyarrow_table: Table = pyarrow_ds.to_table(filter=row_filter, columns=columns)
  File "pyarrow/_dataset.pyx", line 331, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 2577, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
pyo3_runtime.PanicException: dispatch dropped without returning error
```

**What you expected to happen**:

Table is read normally as in 0.6.1. However, inlining credentials didn't work in 0.6.1 either, so we used approach with adding custom filesystem in here: `to_pyarrow_dataset(.., filesystem=...)` where we used a filesystem from `adls` package and everything worked fine.

If I remove custom FS implementation, the exception above occurs. If I leave our custom FS implementation:

```
    def get_pyarrow_filesystem(self, path: DataPath) -> PyFileSystem:

        connection_options = self.connect_storage(path=path) # returns connection credentials for the supplied path
        file_system = AzureBlobFileSystem(
            account_name = connection_options['AZURE_STORAGE_ACCOUNT_NAME'],
            credential = connection_options['AZURE_STORAGE_ACCOUNT_KEY']
        )

        return PyFileSystem(FSSpecHandler(file_system))
```

I get:

```
>>> df = load(azure_client, adls_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/users/gzu/source/repos/github/proteus/proteus/storage/delta_lake/_functions.py", line 48, in load
    pyarrow_table: Table = pyarrow_ds.to_table(filter=row_filter, columns=columns)
  File "pyarrow/_dataset.pyx", line 331, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 2577, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/_fs.pyx", line 1544, in pyarrow._fs._cb_open_input_file
  File "/home/xami/.cache/pypoetry/virtualenvs/proteus-8AsjLY-7-py3.9/lib/python3.9/site-packages/pyarrow/fs.py", line 418, in open_input_file
    raise FileNotFoundError(path)
FileNotFoundError: part-00000-295a0af4-1d98-43ae-adf9-bb5334199693-c000.snappy.parquet
```

Which seems to be related to https://github.com/delta-io/delta-rs/issues/880.

**How to reproduce it**:

Try to read a delta table from ADLS2 with inlined credentials OR read a delta table from ADLS2 using the `get_pyarrow_filesystem` method I've shown above, like this:
```
pyarrow_ds = DeltaTable(path.to_delta_rs_path(), version=version, storage_options=proteus_client.connect_storage(path)) \
        .to_pyarrow_dataset(parquet_read_options=ParquetReadOptions(coerce_int96_timestamp_unit="ms"), filesystem=get_pyarrow_filesystem(path))
```

This requires you having `adlfs = { version = '~2022' }` package installed from PyPi.
**More details**:

**Comment by george-zubrienko** [comment]
Workaround posted here https://github.com/delta-io/delta-rs/issues/880#issuecomment-1280645004
