### ISSUE TITLE
Python write_deltalake to S3 fails to write due to "invalid json"

### ISSUE THREAD

**Issue by joshuarobinson** [delta-io/delta-rs#883]
# Environment

**Delta-rs version**: 0.6.2

**Binding**: Python

**Environment**: Ubuntu 22.04, Python 3.10, deltalake==0.6.2, Running against non-AWS S3 (Swift)

***
# Bug

**What happened**:
DeltaLake write fails.

My test code to write 'df' (a pandas dataframe) to an S3 location:
```
storage_options = {"AWS_ACCESS_KEY_ID": ACCESS_KEY, "AWS_SECRET_ACCESS_KEY":SECRET_KEY, "AWS_ENDPOINT_URL": ENDPOINT_URL, "AWS_REGION": 'us-east-1'}
write_deltalake('s3://joshuarobinson/test_deltalake/', df, storage_options=storage_options)
```
fails with the following error:
```
Traceback (most recent call last):
  File "/delta_write.py", line 19, in <module>
    write_deltalake('s3://joshuarobinson/test_deltalake/', df, storage_options=storage_options)
  File "/usr/local/lib/python3.10/site-packages/deltalake/writer.py", line 156, in write_deltalake
    table = try_get_deltatable(table_or_uri)
  File "/usr/local/lib/python3.10/site-packages/deltalake/writer.py", line 332, in try_get_deltatable
    return DeltaTable(table_uri)
  File "/usr/local/lib/python3.10/site-packages/deltalake/table.py", line 91, in __init__
    self._table = RawDeltaTable(
deltalake.PyDeltaTableError: Failed to load checkpoint: Invalid JSON in checkpoint: expected value at line 1 column 1
```

Note that the destination path is empty, i.e., I'm writing a brand new table
```
$ s5cmd ls s3://joshuarobinson/test_deltalake/
ERROR "ls s3://joshuarobinson/test_deltalake/": no object found
```

Also tried: 
 1) I have tested with all four values of "mode" and had the same result.
 2) also tried to manually build a pyarrow filesystem and pass that but did not work.

**Comment by Thelin90** [comment]
@joshuarobinson I have the same issue.

Looking at the code, it currently expects the table to already exist:

`write_deltalake` performs:

```python
    if isinstance(table_or_uri, str):
        if "://" in table_or_uri:
            table_uri = table_or_uri
        else:
            # Non-existant local paths are only accepted as fully-qualified URIs
            table_uri = "file://" + str(Path(table_or_uri).absolute())
        table = try_get_deltatable(table_or_uri)
    else:
        table = table_or_uri
        table_uri = table._table.table_uri()
```

When `try_get_deltatable` is called, it then calls `DeltaTable`.

It seems like it wants `storage_options` to initialise a new delta table but currently it does not pass it through.

Strange behaviour indeed.

**Comment by wjones127** [comment]
> It seems like it wants `storage_options` to initialise a new delta table but currently it does not pass it through, even if you send it with `write_deltatable`.

Thanks for pointing that out. That indeed isn't the correct logic.

If that's the case, does the following work for you?

```python
storage_options = {"AWS_ACCESS_KEY_ID": ACCESS_KEY, "AWS_SECRET_ACCESS_KEY":SECRET_KEY, "AWS_ENDPOINT_URL": ENDPOINT_URL, "AWS_REGION": 'us-east-1'}
table = DeltaTable('s3://joshuarobinson/test_deltalake/', storage_options=storage_options)
write_deltalake(table, df, storage_options=storage_options)
```

**Comment by Thelin90** [comment]
@wjones127 sorry for late reply!

This does not work for me unfortunately!

**Comment by wjones127** [comment]
> It does not seem like the code will write a delta if there is no delta to begin with.

If that were that were the case, the unit tests wouldn't pass 😄 : https://github.com/delta-io/delta-rs/blob/6492ab36b8c108cc7f8fee1bf8e79a83780ef03f/python/tests/test_writer.py#L42-L46

Something else must being going wrong.

**Comment by Thelin90** [comment]
> > It does not seem like the code will write a delta if there is no delta to begin with.
> 
> If that were that were the case, the unit tests wouldn't pass 😄 :
> 
> https://github.com/delta-io/delta-rs/blob/6492ab36b8c108cc7f8fee1bf8e79a83780ef03f/python/tests/test_writer.py#L42-L46
> 
> Something else must being going wrong.

However this is writing the delta table locally? I'm sure if you do this towards a Minio or S3 it won't work.

**Comment by wjones127** [comment]
> This will just complain that the table does not exist.

Do you have a traceback for this? It would be helpful to know where that exception is being generated (when using the alternative code I provided).

**Comment by Thelin90** [comment]
> > This will just complain that the table does not exist.
> 
> Do you have a traceback for this? It would be helpful to know where that exception is being generated (when using the alternative code I provided).

@wjones127 

```bash
Traceback (most recent call last):
  File "/Users/simon/code/deiteo-code/tfd-to-bronze/run.py", line 33, in <module>
    process.load(data=data, table_name=table_name)
  File "/Users/simon/code/deiteo-code/tfd-to-bronze/src/process.py", line 21, in load
    self.write.file(data=table_data, table_name=table_name)
  File "/Users/simon/code/deiteo-code/tfd-to-bronze/src/sink/write.py", line 22, in file
    delta_table = DeltaTable(table_uri=table_uri, storage_options=self.delta_rs_config.storage_options)
  File "/Users/simon/Library/Caches/pypoetry/virtualenvs/tfd-to-bronze-vlZgp58q-py3.9/lib/python3.9/site-packages/deltalake/table.py", line 91, in __init__
    self._table = RawDeltaTable(
deltalake.PyDeltaTableError: Not a Delta table: No snapshot or version 0 found, perhaps s3://bucket-dev/path/bronze/table is an empty dir?
```

It simply just says the table does not exist doing it this way.

Currently working around this by creating the tables via `trino`.



```python
        df = pd.DataFrame([data])
        table = pa.Table.from_pandas(df)
        table_uri = f"{self.delta_rs_config.table_or_uri}/bronze/{table_name}_new"
        delta_table = DeltaTable(table_uri=table_uri, storage_options=self.delta_rs_config.storage_options)
        try:
            write_deltalake(
                table_or_uri=delta_table,
                data=table,
                overwrite_schema=True,
            )

        # TODO: Too broad
        except Exception as error:
            raise error
```

**Comment by joshuarobinson** [comment]
I can (belatedly) confirm that I'm seeing the same traceback as @Thelin90 when using the alternative code.
```
Traceback (most recent call last):
  File "/delta_write.py", line 19, in <module>
    table = DeltaTable('s3://joshuarobinson/test_deltalake/', storage_options=storage_options)
  File "/usr/local/lib/python3.10/site-packages/deltalake/table.py", line 91, in __init__
    self._table = RawDeltaTable(
deltalake.PyDeltaTableError: Not a Delta table: No snapshot or version 0 found, perhaps s3://joshuarobinson/test_deltalake is an empty dir?
```

**Comment by shazamkash** [comment]
I can also confirm that I am also facing a similar issue.

```
     81 """
     82 Create the Delta Table from a path with an optional version.
     83 Multiple StorageBackends are currently supported: AWS S3, Azure Data Lake Storage Gen2, Google Cloud Storage (GCS) and local URI.
   (...)
     88 :param storage_options: a dictionary of the options to use for the storage backend
     89 """
     90 self._storage_options = storage_options
---> 91 self._table = RawDeltaTable(
     92     table_uri, version=version, storage_options=storage_options
     93 )
     94 self._metadata = Metadata(self._table)

PyDeltaTableError: Not a Delta table: No snapshot or version 0 found, perhaps s3a://kafka-shazam/delta_test/rs_test is an empty dir?
```

**Comment by Thelin90** [comment]
I currently get `SignatureDoesNotMatch`, atm when providing credentials.

**Comment by Thelin90** [comment]
I am working around this now by:

* Create the delta table locally
* Upload table to s3 via s3fs

**Comment by joshuarobinson** [comment]
Any update on this issue?

I've tried again with the most recent release (0.6.3) and get a different error now:

```
Traceback (most recent call last):
  File "/delta_write.py", line 28, in <module>
    write_deltalake('s3://joshuarobinson/test_deltalake/delta/', df, storage_options=storage_options)
  File "/usr/local/lib/python3.10/site-packages/deltalake/writer.py", line 254, in write_deltalake
    ds.write_dataset(
  File "/usr/local/lib/python3.10/site-packages/pyarrow/dataset.py", line 988, in write_dataset
    _filesystemdataset_write(
  File "pyarrow/_dataset.pyx", line 2859, in pyarrow._dataset._filesystemdataset_write
deltalake.PyDeltaTableError: Generic S3 error: Error performing put request test_deltalake/delta/0-95c345d7-1a11-4e5a-9983-e379286e480c-0.parquet: response error "request error", after 0 retries: error sending request for url (https://pbss.s8k.io/joshuarobinson/test_deltalake/delta/0-95c345d7-1a11-4e5a-9983-e379286e480c-0.parquet?partNumber=1&uploadId=OGIzN2E3YWMtYjRmNS00OTQ0LWIxYmUtYmQ1OWUyZjY1MjQw): error trying to connect: tcp connect error: IO driver has terminated
```

my write command looks like this:
```
write_deltalake('s3://joshuarobinson/test_deltalake/delta/', df, storage_options=storage_options)
```

(note that the storage_options work when reading the delta table's metadata, so probably not an error there)

**Comment by wjones127** [comment]
> Any update on this issue?

Yes, I had fixed the previous errors and added integration tests. So these are new issues, and ones that aren't captured by our current integration tests :(

That sounds like one of the threads had panicked, and the write tasks are returning an error. I'll spend some time looking into that soon.

**Comment by Thelin90** [comment]
I can confirm it still does not work for me either with the latest version.

**Comment by wjones127** [comment]
We just released 0.6.4, which should fix this issue. Could you confirm that `write_deltalake` is now working for you?

**Comment by shazamkash** [comment]
@wjones127 

When I try with the following example provided in the documentation
```
df = pd.DataFrame({'x': [1, 2, 3]})
write_table_path = "s3a://kafka-shazam/delta_test/rs_test/"
dl.write_deltalake(write_table_path, df, storage_options=storage_options)

```

I get the following error:

```
---------------------------------------------------------------------------
PyDeltaTableError                         Traceback (most recent call last)
Input In [7], in <cell line: 3>()
      1 df = pd.DataFrame({'x': [1, 2, 3]})
      2 write_table_path = "s3a://kafka-shazam/delta_test/rs_test/"
----> 3 dl.write_deltalake(write_table_path, df, storage_options=storage_options)



File /opt/conda/lib/python3.9/site-packages/deltalake/writer.py:269, in write_deltalake(table_or_uri, data, schema, partition_by, filesystem, mode, file_options, max_open_files, max_rows_per_file, min_rows_per_group, max_rows_per_group, name, description, configuration, overwrite_schema, storage_options)
    250 ds.write_dataset(
    251     data,
    252     base_dir="/",
   (...)
    265     filesystem=filesystem,
    266 )
    268 if table is None:
--> 269     _write_new_deltalake(
    270         table_uri,
    271         schema,
    272         add_actions,
    273         mode,
    274         partition_by or [],
    275         name,
    276         description,
    277         configuration,
    278         storage_options,
    279     )
    280 else:
    281     table._table.create_write_transaction(
    282         add_actions,
    283         mode,
    284         partition_by or [],
    285         schema,
    286     )



PyDeltaTableError: Failed to read delta log object: Generic DeltaS3ObjectStore error: Atomic rename requires a LockClient for S3 backends. Either configure the LockClient, or set AWS_S3_ALLOW_UNSAFE_RENAME=true to opt out of support for concurrent writers.

```

But in my S3 bucket, I can see the table being created, as seen below but the delta log does not look fine as it has this .tmp at the end. Also, I cannot read this table.

![image](https://user-images.githubusercontent.com/36969412/204518347-abcd9f50-32c0-42e2-acca-f62c66f3eb06.png)


![image](https://user-images.githubusercontent.com/36969412/204518452-69533880-b916-49a4-8845-4b6cc207a23b.png)


I have also tried writing table the following way:

```
table = dl.DeltaTable('s3a://kafka-shazam/delta_test/rs_test', storage_options=storage_options)
dl.write_deltalake(table, df, storage_options=storage_options)

```

Here is the error for this code:

```
---------------------------------------------------------------------------
PyDeltaTableError                         Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 table = dl.DeltaTable('s3a://kafka-shazam/delta_test/rs_test', storage_options=storage_options)
      2 dl.write_deltalake(table, df, storage_options=storage_options)

File /opt/conda/lib/python3.9/site-packages/deltalake/table.py:103, in DeltaTable.__init__(self, table_uri, version, storage_options, without_files)
     90 """
     91 Create the Delta Table from a path with an optional version.
     92 Multiple StorageBackends are currently supported: AWS S3, Azure Data Lake Storage Gen2, Google Cloud Storage (GCS) and local URI.
   (...)
    100                       DeltaTable will be loaded with a significant memory reduction.
    101 """
    102 self._storage_options = storage_options
--> 103 self._table = RawDeltaTable(
    104     table_uri,
    105     version=version,
    106     storage_options=storage_options,
    107     without_files=without_files,
    108 )
    109 self._metadata = Metadata(self._table)

PyDeltaTableError: Not a Delta table: No snapshot or version 0 found, perhaps s3a://kafka-shazam/delta_test/rs_test is an empty dir?


```

**Comment by wjones127** [comment]
@shazamkash Did you read the error message from the write?

> PyDeltaTableError: Failed to read delta log object: Generic DeltaS3ObjectStore error: Atomic rename requires a LockClient for S3 backends. Either configure the LockClient, or set AWS_S3_ALLOW_UNSAFE_RENAME=true to opt out of support for concurrent writers.

The writer tried to make the table, but couldn't complete the commit. That is why there is a `tmp` file. This error message is intentional.

If you add `AWS_S3_ALLOW_UNSAFE_RENAME=true` (either as an environment variable or in `storage_options`), it should write successfully.

**Comment by shazamkash** [comment]
@wjones127 
> If you add `AWS_S3_ALLOW_UNSAFE_RENAME=true` (either as an environment variable or in `storage_options`), it should write successfully.

Thanks for your help. Writing the delta table does work now for the example in documentation.

Now another problem is when I try to write any other large dataframe, I get the following error:

```

PyDeltaTableError: Generic S3 error: Error performing complete multipart request: response error "<?xml version="1.0" encoding="UTF-8"?><Error><Code>EntityTooSmall</Code><BucketName>kafka-shazam</BucketName><RequestId>tx00000b6e0ebdcf5b90da8-0063869453-35b55ff45-default</RequestId><HostId>35b55ff45-default-default</HostId></Error>", after 0 retries: HTTP status client error (400 Bad Request) for url (https://es-si-s3-z2.eecloud.nsn-net.net/kafka-shazam/delta_test/rs_test/0-4b41fe34-3605-4b3c-8cd9-2ab61eb8f34a-0.parquet?uploadId=2%7EhY7nplOyckHBl7ePcT67gt77ySSzIpJ)

**Comment by shazamkash** [comment]
I am also facing this error with some datasets; I am not entirely sure if this is related, or I must open a new issue. These datasets work fine when reading with pandas or pyarrow. Also, I am able to upload them to delta lake using pyspark.

```

IndexError: 0 out of bounds
Exception ignored in: 'pyarrow._dataset._filesystemdataset_write_visitor'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/deltalake/writer.py", line 208, in visitor
    stats = get_file_stats_from_metadata(written_file.metadata)
  File "/opt/conda/lib/python3.9/site-packages/deltalake/writer.py", line 369, in get_file_stats_from_metadata
    name = metadata.row_group(0).column(column_idx).path_in_schema
  File "pyarrow/_parquet.pyx", line 769, in pyarrow._parquet.FileMetaData.row_group
  File "pyarrow/_parquet.pyx", line 506, in pyarrow._parquet.RowGroupMetaData.__cinit__
IndexError: 0 out of bounds

**Comment by shazamkash** [comment]
@wjones127 

Can you please share some more information or some resources where I can get to know more about how to configure this LockClient for S3 backends in case I want to use concurrent writers.

**Comment by Thelin90** [comment]
I can now verify this works directly to S3 with 0.6.4

However I do need to set:

`AWS_S3_ALLOW_UNSAFE_RENAME=true`

**Comment by ddangu525** [comment]
`write_deltalake` function
```python
...
if isinstance(table_or_uri, str):
    if "://" in table_or_uri:
        table_uri = table_or_uri
    else:
        # Non-existant local paths are only accepted as fully-qualified URIs
        table_uri = "file://" + str(Path(table_or_uri).absolute())
    # table = try_get_deltatable(table_or_uri) # wrong?
    table = try_get_deltatable(table_uri)
else:
    table = table_or_uri
    table_uri = table._table.table_uri()
```
Shouldn't `table_uri`, not `table_or_uri`, be the argument of `try_get_deltatable` in the first if statement of above code?

I've also been having a problem writing to my minio storage.
```python
MINIO_URI = 'https://minio_api_uri'
storage_options = {
    "AWS_ACCESS_KEY_ID": ACCESS_KEY,
    "AWS_SECRET_ACCESS_KEY": SECRET
}
write_deltalake(f'{MINIO_URI}/bucket/delta_path', data=df, storage_options=storage_options)
```
It returns `pyo3_runtime.PanicException: not yet implemented` exception.

**Comment by ion-elgreco** [comment]
Closing this one since it's stale
