### ISSUE TITLE
Write mode doesn't work with Azure storage

### ISSUE THREAD

**Issue by Anna050689** [delta-io/delta-rs#955]
# Environment

**Delta-rs version**: 0.6.3

**Binding**: python 3.9.13

**Environment**:
- **Cloud provider**: Azure
- **OS**: Windows
- **Other**:

***
# Bug

**What happened**:
There is an error when I try to write the dataframe to Azure Storage with provided valid credentials - AZURE_STORAGE_CONNECTION_STRING, AZURE_STORAGE_CONTAINER_NAME, AZURE_STORAGE_BLOB_NAME.

**What you expected to happen**:
I expect to write dataframe to the file

**How to reproduce it**:
```
from typing import Optional
import os

from deltalake import PyDeltaTableError
import pandas as pd
from deltalake.writer import write_deltalake


def save_data(path: Optional[str], df: pd.DataFrame, storage_options):
    """
    Save data in Delta format to Azure Storage

    :param
    path:
    str which should be should be in the next format for the connection to Azure Storage: "azure://{container_name}/{blob_name}"
    """
    if df is not None:
        try:
            write_deltalake(path, df, storage_options=storage_options)
        except PyDeltaTableError as error:
            if "Missing configuration AZURE_STORAGE_ACCOUNT" in error.args[0] \
                    or "Failed to find valid credential" in error.args[0]:
                message = f"It seems that the authentication to Azure Storage was failed due to absent or " \
                          f"invalid credentials.\nThe details of the error - {error}\n" \
                          f"Please set up valid credentials in order to write the table to {path}."
                print(message)
                raise PermissionError(message)
            elif 'A socket operation was attempted to an unreachable network' in error.args[0] \
                    or 'Failed to read checkpoint content: Generic S3 error' in error.args[0]:
                message = f"It seems that the authentication to AWS S3 bucket was failed due to absent or " \
                          f"invalid credentials.\nThe details of the error - {error}\n" \
                          f"Please set up valid credentials in order to write the table to {path}."
                print(message)
                raise PermissionError(message)


if __name__ == "__main__":
    df = pd.DataFrame([['Name', 'Surname'], ['Anna', 'Girl']])
    save_data(
        "azure://databricks/deltafiles/TestDimDate",
        df,
        storage_options={
            "AZURE_STORAGE_ACCOUNT_NAME": os.getenv("AZURE_STORAGE_ACCOUNT_NAME"),
            "AZURE_STORAGE_ACCOUNT_KEY": os.getenv("AZURE_STORAGE_ACCOUNT_KEY"),
            "AZURE_STORAGE_CONNECTION_STRING": os.getenv("AZURE_STORAGE_CONNECTION_STRING")
        })

```
**More details**:
Traceback of the error:
```
Traceback (most recent call last):
  File "C:\Users\Hanna_Imshenetska\Projects\Project_for_selfeducation\loader\write_delta_table.py", line 39, in <module>
    save_data(
  File "C:\Users\Hanna_Imshenetska\Projects\Project_for_selfeducation\loader\write_delta_table.py", line 19, in save_data
    write_deltalake(path, df, storage_options=storage_options)
  File "C:\Users\Hanna_Imshenetska\Projects\Project_for_selfeducation\venv\lib\site-packages\deltalake\writer.py", line 168, in write_deltalake
    storage_options = dict(
TypeError: dict() got multiple values for keyword argument 'AZURE_STORAGE_ACCOUNT_NAME
```

**Comment by 0xdarkman** [comment]
I do experience same error

deltalake 0.6.3


```
import pandas as pd
from deltalake.writer import write_deltalake


account_name = "AAA"
account_key = "BBB"


write_deltalake(
        table_or_uri="abfss://CONTAINERNAME@STORAGEACCOUNT.dfs.core.windows.net/TABLENAME",
        data=df,
        mode="overwrite",
        storage_options = {
                "AZURE_STORAGE_ACCOUNT_NAME": account_name,
                "AZURE_STORAGE_ACCOUNT_KEY": account_key,
            },
    )
```


```
**(table._storage_options or {}), **(storage_options or {})
TypeError: type object got multiple values for keyword argument 'AZURE_STORAGE_ACCOUNT_NAME'
```

**Comment by 0xdarkman** [comment]
```
storage_options = {
  "AZURE_STORAGE_ACCOUNT_NAME": account_name, 
  "AZURE_STORAGE_ACCOUNT_KEY": account_key,
}

table_path = "abfss://CONTAINERNAME@STORAGEACCOUNT.dfs.core.windows.net/iana_tlds"
dt = DeltaTable(table_path, storage_options=storage_options)

write_deltalake(table_or_uri=dt, df=df, mode="overwrite")
```

**Comment by 0xdarkman** [comment]
remember to do

```
import pyarrow as pa
tb = pa.Table.from_pandas(df, preserve_index=False)
write_deltalake(table_or_uri=dt, data=tb, mode="overwrite")
```
